/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.NhapXeDAO;
import DTO.NhapXeDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class PFNhanXe extends javax.swing.JPanel {

    /**
     * Creates new form PFReceiveCar
     */
    public PFNhanXe() {
        initComponents();
        setSize(1040, 545);
        autoDate();
        autoTime();
        loadChonVe();
        loadLoaiXe();
        String loaixe = cbxLoaiXe.getSelectedItem().toString();
        String loaive = cbxLoaive.getSelectedItem().toString();

        loadMave(loaive);
        loadcbxKhuVuc(loaixe, loaive);
        loadcbxViTri(loaive);
    }

    private void autoDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        txtNgaynhan.setText(s.format(d));
    }

    private void autoTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                txtGionhan.setText(s.format(d));
            }
        }).start();
    }

    private void loadChonVe() {
        ArrayList<String> list = NhapXeDAO.LoadComboBoxChonVe();
        cbxLoaive.removeAllItems();
        for (String item : list) {
            cbxLoaive.addItem(item.toString());
        }
    }

    private void loadMave(String loaive) {
        ArrayList<String> list = NhapXeDAO.LoadComboBoxMaVe(loaive);
        cbxMave.removeAllItems();
        for (String item : list) {
            cbxMave.addItem(item.toString());
        }
    }

    private void loadLoaiXe() {
        ArrayList<String> list = NhapXeDAO.LoadcbxLoaiXe();
        cbxLoaiXe.removeAllItems();
        for (String item : list) {
            cbxLoaiXe.addItem(item.toString());
        }
    }

    private void loadcbxKhuVuc(String loaixe, String loaive) {
        ArrayList<String> list = NhapXeDAO.LoadcbxKhuVuc(loaixe, loaive);
        cbxKhuVuc.removeAllItems();
        for (String item : list) {
            cbxKhuVuc.addItem(item.toString());
        }
    }

    private void loadcbxViTri(String loaive) {
        ArrayList<String> list = NhapXeDAO.LoadcbxViTri(loaive);
        cbxViTri.removeAllItems();
        for (String item : list) {
            cbxViTri.addItem(item.toString());
        }
    }

    public NhapXeDTO addXe() {
        NhapXeDTO themxe = new NhapXeDTO();
        themxe.setBienSo(txtBienso.getText());
        themxe.setLoaiXe(cbxLoaiXe.getSelectedItem().toString());
        themxe.setLoaiVe(cbxLoaive.getSelectedItem().toString());
        themxe.setMaVe(cbxMave.getSelectedItem().toString());
        themxe.setMauXe(txtMauxe.getText());
        themxe.setKhuVuc(cbxKhuVuc.getSelectedItem().toString());
        if (cbxLoaiXe.getSelectedItem().toString().equals("Xe máy")) {
            themxe.setViTri("");
        } else {
            themxe.setViTri(cbxViTri.getSelectedItem().toString());
        }
        themxe.setNgayGui(LocalDate.parse(txtNgaynhan.getText()));
        themxe.setGioGui(txtGionhan.getText());
        return themxe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxLoaive = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cbxMave = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtBienso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMauxe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxLoaiXe = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxKhuVuc = new javax.swing.JComboBox<>();
        cbxViTri = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtNgaynhan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGionhan = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Image/icons8_bank_cards_32px.png"))); // NOI18N
        jLabel1.setText("Loại Vé : ");

        cbxLoaive.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxLoaive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxLoaive.setBorder(null);
        cbxLoaive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxLoaive.setFocusable(false);
        cbxLoaive.setName("cbxLoaive"); // NOI18N
        cbxLoaive.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLoaiveItemStateChanged(evt);
            }
        });
        cbxLoaive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiveActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã Vé : ");

        cbxMave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxMave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxMave.setBorder(null);
        cbxMave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxMave.setFocusable(false);
        cbxMave.setName("cbxMave"); // NOI18N
        cbxMave.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMaveItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Biển Số Xe :");

        txtBienso.setBackground(new java.awt.Color(204, 204, 204));
        txtBienso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBienso.setBorder(null);
        txtBienso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBienso.setName("txtBienso"); // NOI18N
        txtBienso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiensoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Màu Xe :");

        txtMauxe.setBackground(new java.awt.Color(204, 204, 204));
        txtMauxe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMauxe.setBorder(null);
        txtMauxe.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMauxe.setName("txtMauxe"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Loại Xe :");

        cbxLoaiXe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxLoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxLoaiXe.setBorder(null);
        cbxLoaiXe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxLoaiXe.setFocusable(false);
        cbxLoaiXe.setName("cbxLoaiXe"); // NOI18N
        cbxLoaiXe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLoaiXeItemStateChanged(evt);
            }
        });
        cbxLoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiXeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Khu Vực :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Vị Trí :");
        jLabel7.setToolTipText("");

        cbxKhuVuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxKhuVuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxKhuVuc.setBorder(null);
        cbxKhuVuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxKhuVuc.setFocusable(false);
        cbxKhuVuc.setName("cbxKhuVuc"); // NOI18N
        cbxKhuVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKhuVucActionPerformed(evt);
            }
        });

        cbxViTri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxViTri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxViTri.setBorder(null);
        cbxViTri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxViTri.setFocusable(false);
        cbxViTri.setName("cbxViTri"); // NOI18N
        cbxViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxViTriActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Ngày Nhận :");

        txtNgaynhan.setBackground(new java.awt.Color(204, 204, 204));
        txtNgaynhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNgaynhan.setBorder(null);
        txtNgaynhan.setName("txtNgaynhan"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Giờ Nhận :");

        txtGionhan.setBackground(new java.awt.Color(204, 204, 204));
        txtGionhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGionhan.setBorder(null);
        txtGionhan.setName("txtGionhan"); // NOI18N
        txtGionhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGionhanActionPerformed(evt);
            }
        });

        btnXacNhan.setBackground(new java.awt.Color(204, 204, 204));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.setBorder(null);
        btnXacNhan.setBorderPainted(false);
        btnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhan.setName("btnXacNhan"); // NOI18N
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(txtBienso, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxMave, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMauxe, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(cbxLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(60, 60, 60)
                                    .addComponent(cbxViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgaynhan, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGionhan, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbxLoaive, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxLoaive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtNgaynhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbxMave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtGionhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtBienso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtMauxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(109, 109, 109)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxViTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxViTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxViTriActionPerformed

    private void cbxKhuVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKhuVucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxKhuVucActionPerformed

    private void cbxLoaiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaiveActionPerformed

    private void cbxLoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaiXeActionPerformed

    private void txtGionhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGionhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGionhanActionPerformed

    private void txtBiensoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiensoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiensoActionPerformed

    private void cbxLoaiXeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLoaiXeItemStateChanged
        // TODO add your handling code here:
        cbxLoaiXe = (JComboBox<String>) evt.getSource();
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String loaixe = cbxLoaiXe.getSelectedItem().toString();
            String loaive = cbxLoaive.getSelectedItem().toString();
            if (cbxLoaive.getSelectedItem().toString().equals("Vé Ngày")) {
                if (cbxLoaiXe.getSelectedItem().toString().equals("Ô tô")) {
                    loadcbxKhuVuc("Ô tô", loaive);
                    loadcbxViTri(loaive);
                    cbxViTri.setEnabled(true);
                } else if (cbxLoaiXe.getSelectedItem().toString().equals("Xe máy")) {
                    loadcbxKhuVuc("Xe máy", loaive);
                    cbxViTri.setEnabled(false);
                    cbxViTri.removeAllItems();
                }
            } else if (cbxLoaive.getSelectedItem().toString().equals("Vé Tháng")) {
                if (cbxLoaiXe.getSelectedItem().toString().equals("Ô tô")) {
                    loadcbxKhuVuc("Ô tô", loaive);
                    loadcbxViTri(loaive);
                    cbxViTri.setEnabled(true);
                } else if (cbxLoaiXe.getSelectedItem().toString().equals("Xe máy")) {
                    loadcbxKhuVuc("Xe máy", loaive);
                    cbxViTri.setEnabled(false);
                    cbxViTri.removeAllItems();
                }
            }
        }
    }//GEN-LAST:event_cbxLoaiXeItemStateChanged

    private void cbxLoaiveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLoaiveItemStateChanged
        cbxLoaive = (JComboBox<String>) evt.getSource();
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String loaixe = cbxLoaiXe.getSelectedItem().toString();
            String loaive = cbxLoaive.getSelectedItem().toString();
            String khuvuc = cbxKhuVuc.getSelectedItem().toString();
            if (cbxLoaive.getSelectedItem().toString().equals("Vé Ngày")) {
                if (cbxLoaiXe.getSelectedItem().toString().equals("Xe máy")) {
                    cbxLoaiXe.setEnabled(true);
                    cbxKhuVuc.setEnabled(true);
                    txtBienso.setEnabled(true);
                    txtMauxe.setEnabled(true);
                    txtBienso.setText("");
                    txtMauxe.setText("");
                    cbxViTri.removeAllItems();
                    cbxKhuVuc.removeAllItems();
                    loadcbxKhuVuc(loaixe, loaive);
                    loadMave(loaive);
                } else if (cbxLoaiXe.getSelectedItem().toString().equals("Ô tô")) {
                    cbxLoaiXe.setEnabled(true);
                    cbxKhuVuc.setEnabled(true);
                    txtBienso.setEnabled(true);
                    txtMauxe.setEnabled(true);
                    txtBienso.setText("");
                    txtMauxe.setText("");
                    cbxViTri.removeAllItems();
                    cbxKhuVuc.removeAllItems();
                    loadcbxKhuVuc(loaixe, loaive);
                    loadcbxViTri(loaive);
                    loadMave(loaive);
                }
            } else if (cbxLoaive.getSelectedItem().toString().equals("Vé Tháng")) {
                if (cbxLoaiXe.getSelectedItem().toString().equals("Ô tô")) {
                    cbxLoaiXe.setEnabled(false);
                    cbxKhuVuc.setEnabled(false);
                    txtBienso.setEnabled(false);
                    txtMauxe.setEnabled(false);
                    cbxViTri.removeAllItems();
                    cbxKhuVuc.removeAllItems();
                    loadMave(loaive);
                    loadcbxKhuVuc(loaixe, loaive);
                    loadcbxViTri(loaive);
                } else if (cbxLoaiXe.getSelectedItem().toString().equals("Xe máy")) {
                    cbxLoaiXe.setEnabled(false);
                    cbxKhuVuc.setEnabled(false);
                    txtBienso.setEnabled(false);
                    txtMauxe.setEnabled(false);
                    cbxViTri.removeAllItems();
                    cbxKhuVuc.removeAllItems();
                    loadcbxKhuVuc(loaixe, loaive);
                    loadMave(loaive);
                }

            }
        }
    }//GEN-LAST:event_cbxLoaiveItemStateChanged

    private void cbxMaveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMaveItemStateChanged
        // TODO add your handling code here:
        cbxMave = (JComboBox<String>) evt.getSource();
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (cbxLoaive.getSelectedItem().toString().equals("Vé Tháng")) {
                String loaive = cbxLoaive.getSelectedItem().toString();
                String loaixe = cbxLoaiXe.getSelectedItem().toString();
                String mave = cbxMave.getSelectedItem().toString();
                NhapXeDAO nxa = new NhapXeDAO();
                NhapXeDTO nxt = nxa.load2Text(mave);
                if (nxt != null) {
                    txtBienso.setText(nxt.getBienSo());
                    txtMauxe.setText(nxt.getMauXe());
                    cbxLoaiXe.setSelectedItem(nxt.getLoaiXe());
                    if (cbxLoaiXe.getSelectedItem().toString().equals("Ô tô")) {
                        loadcbxViTri(loaive);
                    } 
                }
            }
        }
    }//GEN-LAST:event_cbxMaveItemStateChanged

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        try {
            if (cbxLoaiXe.getSelectedItem().toString().equals("Xe máy")) {
                if (txtBienso.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập biển số");
                } else {
                    String checkBienso = txtBienso.getText();
                    String loaive = cbxLoaive.getSelectedItem().toString();
                    String khuvuc = cbxKhuVuc.getSelectedItem().toString();
                    String loaixe = cbxLoaiXe.getSelectedItem().toString();
                    NhapXeDAO nx = new NhapXeDAO();
                    NhapXeDTO checkxe = nx.checkBien(checkBienso);
                    if (checkxe != null) {
                        JOptionPane.showMessageDialog(this, "Xe đã có trong bãi");
                        txtBienso.setText("");
                    } else {
                        NhapXeDTO themxe = addXe();
                        if (nx.ThemXe(themxe) > 0) {
                            JOptionPane.showMessageDialog(this, "Nhập xe thành công!");
                            loadMave(checkBienso);
                            loadLoaiXe();
                            loadChonVe();

                            loadcbxKhuVuc(loaixe, loaive);
                            loadcbxViTri(loaive);
                            txtBienso.setText("");
                            txtMauxe.setText("");
                        } else {
                            JOptionPane.showMessageDialog(this, "Nhập xe thất bại!");
                        }
                    }
                }
            } else {
                if (txtBienso.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập biển số");
                } else {
                    String checkBienso = txtBienso.getText();
                    NhapXeDAO nx = new NhapXeDAO();
                    NhapXeDTO checkxe = nx.checkBien(checkBienso);
                    if (checkxe != null) {
                        JOptionPane.showMessageDialog(this, "Xe đã có trong bãi");
                        txtBienso.setText("");
                    } else {
                        NhapXeDTO themxe = addXe();
                        String loaive = cbxLoaive.getSelectedItem().toString();
                        String khuvuc = cbxKhuVuc.getSelectedItem().toString();
                        String loaixe = cbxLoaiXe.getSelectedItem().toString();
                        if (nx.ThemXe(themxe) > 0) {
                            JOptionPane.showMessageDialog(this, "Nhập xe thành công!");
                            loadMave(checkBienso);
                            loadLoaiXe();
                            loadChonVe();

                            loadcbxKhuVuc(loaixe, loaive);
                            loadcbxViTri(loaive);
                            txtBienso.setText("");
                            txtMauxe.setText("");
                        } else {
                            JOptionPane.showMessageDialog(this, "Nhập xe thất bại!");
                        }
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cbxKhuVuc;
    private javax.swing.JComboBox<String> cbxLoaiXe;
    private javax.swing.JComboBox<String> cbxLoaive;
    private javax.swing.JComboBox<String> cbxMave;
    private javax.swing.JComboBox<String> cbxViTri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtBienso;
    private javax.swing.JTextField txtGionhan;
    private javax.swing.JTextField txtMauxe;
    private javax.swing.JTextField txtNgaynhan;
    // End of variables declaration//GEN-END:variables
}
